#:include kv/loginscreen.kv
#:include kv/homescreen.kv
#:include kv/logintype.kv

FloatLayout:
    WindowManager:
#        size_hint: 1, 0.699
#        pos_hint: {"top": .799, "left": 1}
        id: WindowManager
        LoginScreen:
            name: "login"
            id: login
        LoginType:
            name: 'logintype'
            id: logintype
        HomeScreen:
            name: "home"
            id: home
